"""Shared Literal aliases used across Valorant MCP tools and server."""

from typing import Literal

Region = Literal["eu", "na", "latam", "br", "ap", "kr"]
Platform = Literal["pc", "console"]

GameMode = Literal[
    "competitive",
    "custom",
    "deathmatch",
    "escalation",
    "teamdeathmatch",
    "newmap",
    "replication",
    "snowballfight",
    "spikerush",
    "swiftplay",
    "unrated",
]

MapName = Literal[
    "Ascent",
    "Split",
    "Abyss",
    "Bind",
    "Breeze",
    "Corrode",
    "District",
    "Fracture",
    "Haven",
    "Icebox",
    "Kasbah",
    "Lotus",
    "Piazza",
    "Pearl",
    "Sunset",
]

SeasonShort = Literal[
    "e1a1",
    "e1a2",
    "e1a3",
    "e2a1",
    "e2a2",
    "e2a3",
    "e3a1",
    "e3a2",
    "e3a3",
    "e4a1",
    "e4a2",
    "e4a3",
    "e5a1",
    "e5a2",
    "e5a3",
    "e6a1",
    "e6a2",
    "e6a3",
    "e7a1",
    "e7a2",
    "e7a3",
    "e8a1",
    "e8a2",
    "e8a3",
    "e9a1",
    "e9a2",
    "e9a3",
]

EsportsRegion = Literal[
    "international",
    "north america",
    "emea",
    "brazil",
    "japan",
    "korea",
    "latin_america",
    "latin_america_south",
    "latin_america_north",
    "southeast_asia",
    "vietnam",
    "oceania",
]

League = Literal[
    "vct_americas",
    "challengers_na",
    "game_changers_na",
    "vct_emea",
    "vct_pacific",
    "challengers_br",
    "challengers_jpn",
    "challengers_kr",
    "challengers_latam",
    "challengers_latam_n",
    "challengers_latam_s",
    "challengers_apac",
    "challengers_sea_id",
    "challengers_sea_ph",
    "challengers_sea_sg_and_my",
    "challengers_sea_th",
    "challengers_sea_hk_and_tw",
    "challengers_sea_vn",
    "valorant_oceania_tour",
    "challengers_south_asia",
    "game_changers_sea",
    "game_changers_series_brazil",
    "game_changers_east_asia",
    "game_changers_emea",
    "game_changers_jpn",
    "game_changers_kr",
    "game_changers_latam",
    "game_changers_championship",
    "masters",
    "last_chance_qualifier_apac",
    "last_chance_qualifier_east_asia",
    "last_chance_qualifier_emea",
    "last_chance_qualifier_na",
    "last_chance_qualifier_br_and_latam",
    "vct_lock_in",
    "champions",
    "vrl_spain",
    "vrl_northern_europe",
    "vrl_dach",
    "vrl_france",
    "vrl_east",
    "vrl_turkey",
    "vrl_cis",
    "mena_resilence",
    "challengers_italy",
    "challengers_portugal",
]
